export const LOAD_TVSHOWS_SUCCESS = 'LOAD_TVSHOWS_SUCCESS';  
export const LOAD_TVSHOWS_DETAILS_SUCCESS = 'LOAD_TVSHOWS_DETAILS_SUCCESS'; 
export const LOAD_TVSHOWS_SEASON_DETAILS_SUCCESS = 'LOAD_TVSHOWS_SEASON_DETAILS_SUCCESS'; 
export const LOAD_CONFIG_SUCCESS = 'LOAD_CONFIG_SUCCESS';